name: Auto Update Repo from Endpoint

on:
  schedule:
    - cron: '0 */12 * * *' # every 12 hours
  workflow_dispatch: # allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Fetch data from API and update repo
      env:
        API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
        API_KEY: ${{ secrets.API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        #!/bin/bash
        echo "Fetching content from API..."
        
        # Fetch data
        if [ -z "$API_KEY" ]; then
          curl -s "$API_ENDPOINT" -o hs.m3u
        else
          curl -s -H "Authorization: Bearer $API_KEY" "$API_ENDPOINT" -o hs.m3u
        fi

        # Configure Git
        git config user.name "github-actions"
        git config user.email "actions@github.com"

        # Only commit if data changed
        git add hs.m3u
        if ! git diff --cached --quiet; then
          git commit -m "Auto-update data from Devil's Server."
          git push
          echo "Content updated and pushed."
        else
          echo "No changes detected. Nothing to commit."
